language: ruby
rvm:
- 2.0.0
env:
  global:
  - secure: Rg4MmfZITTnriM36yOaIC5dskxIZbfIdQ6azaUrasPfIl3Llr5+YlZlFs4GHL7gn2BPPz6qBgnURXDP22Sc8KISighCIdHxunvFLt7TwvwlWYCuDvaUdOGpoZq+KZyUzrHfL6gPZetLZXs1AyzloNMifDozTh0mpjOINDplXSz0=
  - secure: zrGsMmYX+bFA4xdC6uaNQd0IitZuf1q5gLcUUlB+YnnlMJ1e2Ry12tOa4OVy72ih0Q/wHGM/8Zg8SJl1frPuew43EqrYfC9ZuMegcosyEmYqS5jEUx5Xn7gxqhIWFadJq14rU5U0yp1mBnVLL8ugNquM7WRykB3mFtbBMWp5IP8=
